// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// This project keeps env vars in .env.local (not the default .env)
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Pooled connection used at runtime
    url: process.env["DATABASE_URL"],
    // Direct, non-pooler connection used by Prisma Migrate
    directUrl: process.env["DIRECT_URL"],
  },
});
